### ISSUE TITLE
Broken URL to Fix

### ISSUE THREAD

**Issue by pascalandy** [xinity/pxc_swarm#1]
https://xinity.github.io/Percona-PXC-Swarm-mode/

> More information: see my blog post

**Comment by xinity** [comment]
fixed right away thanks a lot !

**Comment by pascalandy** [comment]
Very welcome, thanks for sharing this awesome setup. Still didn't tried it. 
Will give you feedback once done :)

**Comment by xinity** [comment]
You're very welcome to give any feedback :)
